steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  secretEnv:
    - GITHUB_ACCESS_TOKEN
  entrypoint: bash
  args:
    - -c
    - |
      echo "Building Docker image..."
      docker build \
        -t "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}" \
        --build-arg GITHUB_ACCESS_TOKEN=$$GITHUB_ACCESS_TOKEN \
        ./app

# Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  waitFor:
    - Build
  args:
    - push
    - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"

images:
- "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:${SHORT_SHA}"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/github-access-token/versions/latest
    env: GITHUB_ACCESS_TOKEN
