steps:

# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - build
    - -t
    - asia-south1-docker.pkg.dev/$PROJECT_ID/demo-repo/production-app:$SHORT_SHA
    - ./app

# Push Docker Image
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - push
    - asia-south1-docker.pkg.dev/$PROJECT_ID/demo-repo/production-app:$SHORT_SHA

# Create Cloud Deploy Release
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: Cloud Deploy Release
  entrypoint: gcloud
  args:
    - deploy
    - releases
    - create
    - release-$SHORT_SHA
    - --delivery-pipeline=production-pipeline
    - --region=asia-south1
    - --images=production-app=asia-south1-docker.pkg.dev/$PROJECT_ID/demo-repo/production-app:$SHORT_SHA

images:
- asia-south1-docker.pkg.dev/$PROJECT_ID/demo-repo/production-app:$SHORT_SHA